# site properties and page defaults
title: PLML Laboratory
subtitle: Programming Languages and Machine Learning
description: Programming Languages and Machine Learning Laboratory at Kangwon National University.
proofer: false

# site social media and other links
links:
  github: knu-plml

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_news
  - scope:
      type: "news"
    values: {}
  - scope:
      type: "publications"
    values:
      layout: publication
  - scope:
      type: "courses"
    values: {}
  - scope:
      type: "gallery"
    values:
      layout: gallery

collections:
  # generate page for each member
  members:
    output: true
  news:
    output: false
  publications:
    output: true
  courses:
    output: false
  gallery:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

gallery_thumbnails:
  width: 800
  height: 500
  quality: 78

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
logo-text: false
